Use html.escape on titles and addresses
An address of the form `Avenue U &, E 33rd St` was causing
ExpatError: not well-formed (invalid token)

Because XML requires it to be encoded as &amp;